spring.application.name=14_microservicio_libros
# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3307/libreriaspring.datasource.username=rootspring.datasource.password=rootspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driverspring.jpa.hibernate.ddl-auto=updatespring.jpa.show-sql=true
# configuracion de propiedades de nombre de tablas y columnas de hibernate
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#tambien la estrategia implicita
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl